[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_project = "FqoqX9JwoazhFRZPVXciW7NKkYLEkUJhy48kVFmPEUz7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sneha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
